/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatSessionView {
  'startTime' : bigint,
  'status' : string,
  'userRole' : UserRole,
  'consentRef' : string,
  'inferenceStatus' : string,
  'endTime' : [] | [bigint],
  'messages' : Array<Message>,
  'metadata' : string,
  'user' : Principal,
  'sessionId' : string,
  'inferenceResponse' : [] | [string],
}
export interface Consent {
  'matchingPermission' : boolean,
  'ownershipHash' : string,
  'timestamp' : bigint,
  'dataUsage' : boolean,
}
export interface Message {
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
}
export interface Profile {
  'bio' : string,
  'social' : SocialLinks,
  'name' : string,
  'role' : UserRole,
  'profession' : string,
}
export interface SocialLinks {
  'linkedin' : [] | [string],
  'twitter' : [] | [string],
  'instagram' : [] | [string],
  'website' : [] | [string],
}
export interface SoulboundToken {
  'principal' : Principal,
  'verified' : boolean,
  'metadata' : string,
  'role' : UserRole,
  'timestamp' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'social' : SocialLinks,
  'name' : string,
  'role' : UserRole,
  'profession' : string,
}
export interface UserRecordView {
  'sbt' : SoulboundToken,
  'createdAt' : bigint,
  'consents' : Array<Consent>,
  'profile' : Profile,
}
export type UserRole = { 'athlete' : null } |
  { 'brand' : null } |
  { 'artist' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addConsent' : ActorMethod<[boolean, boolean, string], undefined>,
  'addMessageToSession' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createBrandBrief' : ActorMethod<[], undefined>,
  'createChatSession' : ActorMethod<[string, string, string], undefined>,
  'createProfile' : ActorMethod<[Profile], undefined>,
  'endChatSession' : ActorMethod<[string], undefined>,
  'getAllChatSessions' : ActorMethod<[], Array<ChatSessionView>>,
  'getAllUserRecords' : ActorMethod<[], Array<UserRecordView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getChatSession' : ActorMethod<[string], [] | [ChatSessionView]>,
  'getConsents' : ActorMethod<[], Array<Consent>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getSBT' : ActorMethod<[], [] | [SoulboundToken]>,
  'getUserChatSessions' : ActorMethod<[], Array<ChatSessionView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
  'updateSessionInference' : ActorMethod<[string, string, string], undefined>,
  'verifySBT' : ActorMethod<[Principal], undefined>,
  'verifyUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];