/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SocialLinks = IDL.Record({
  'linkedin' : IDL.Opt(IDL.Text),
  'twitter' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'athlete' : IDL.Null,
  'brand' : IDL.Null,
  'artist' : IDL.Null,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'social' : SocialLinks,
  'name' : IDL.Text,
  'role' : UserRole,
  'profession' : IDL.Text,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ChatSessionView = IDL.Record({
  'startTime' : IDL.Int,
  'status' : IDL.Text,
  'userRole' : UserRole,
  'consentRef' : IDL.Text,
  'inferenceStatus' : IDL.Text,
  'endTime' : IDL.Opt(IDL.Int),
  'messages' : IDL.Vec(Message),
  'metadata' : IDL.Text,
  'user' : IDL.Principal,
  'sessionId' : IDL.Text,
  'inferenceResponse' : IDL.Opt(IDL.Text),
});
export const SoulboundToken = IDL.Record({
  'principal' : IDL.Principal,
  'verified' : IDL.Bool,
  'metadata' : IDL.Text,
  'role' : UserRole,
  'timestamp' : IDL.Int,
});
export const Consent = IDL.Record({
  'matchingPermission' : IDL.Bool,
  'ownershipHash' : IDL.Text,
  'timestamp' : IDL.Int,
  'dataUsage' : IDL.Bool,
});
export const UserRecordView = IDL.Record({
  'sbt' : SoulboundToken,
  'createdAt' : IDL.Int,
  'consents' : IDL.Vec(Consent),
  'profile' : Profile,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'social' : SocialLinks,
  'name' : IDL.Text,
  'role' : UserRole,
  'profession' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addConsent' : IDL.Func([IDL.Bool, IDL.Bool, IDL.Text], [], []),
  'addMessageToSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createBrandBrief' : IDL.Func([], [], []),
  'createChatSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createProfile' : IDL.Func([Profile], [], []),
  'endChatSession' : IDL.Func([IDL.Text], [], []),
  'getAllChatSessions' : IDL.Func([], [IDL.Vec(ChatSessionView)], ['query']),
  'getAllUserRecords' : IDL.Func([], [IDL.Vec(UserRecordView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getChatSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ChatSessionView)],
      ['query'],
    ),
  'getConsents' : IDL.Func([], [IDL.Vec(Consent)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getSBT' : IDL.Func([], [IDL.Opt(SoulboundToken)], ['query']),
  'getUserChatSessions' : IDL.Func([], [IDL.Vec(ChatSessionView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProfile' : IDL.Func([Profile], [], []),
  'updateSessionInference' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifySBT' : IDL.Func([IDL.Principal], [], []),
  'verifyUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SocialLinks = IDL.Record({
    'linkedin' : IDL.Opt(IDL.Text),
    'twitter' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'athlete' : IDL.Null,
    'brand' : IDL.Null,
    'artist' : IDL.Null,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'social' : SocialLinks,
    'name' : IDL.Text,
    'role' : UserRole,
    'profession' : IDL.Text,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ChatSessionView = IDL.Record({
    'startTime' : IDL.Int,
    'status' : IDL.Text,
    'userRole' : UserRole,
    'consentRef' : IDL.Text,
    'inferenceStatus' : IDL.Text,
    'endTime' : IDL.Opt(IDL.Int),
    'messages' : IDL.Vec(Message),
    'metadata' : IDL.Text,
    'user' : IDL.Principal,
    'sessionId' : IDL.Text,
    'inferenceResponse' : IDL.Opt(IDL.Text),
  });
  const SoulboundToken = IDL.Record({
    'principal' : IDL.Principal,
    'verified' : IDL.Bool,
    'metadata' : IDL.Text,
    'role' : UserRole,
    'timestamp' : IDL.Int,
  });
  const Consent = IDL.Record({
    'matchingPermission' : IDL.Bool,
    'ownershipHash' : IDL.Text,
    'timestamp' : IDL.Int,
    'dataUsage' : IDL.Bool,
  });
  const UserRecordView = IDL.Record({
    'sbt' : SoulboundToken,
    'createdAt' : IDL.Int,
    'consents' : IDL.Vec(Consent),
    'profile' : Profile,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'social' : SocialLinks,
    'name' : IDL.Text,
    'role' : UserRole,
    'profession' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addConsent' : IDL.Func([IDL.Bool, IDL.Bool, IDL.Text], [], []),
    'addMessageToSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createBrandBrief' : IDL.Func([], [], []),
    'createChatSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createProfile' : IDL.Func([Profile], [], []),
    'endChatSession' : IDL.Func([IDL.Text], [], []),
    'getAllChatSessions' : IDL.Func([], [IDL.Vec(ChatSessionView)], ['query']),
    'getAllUserRecords' : IDL.Func([], [IDL.Vec(UserRecordView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getChatSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ChatSessionView)],
        ['query'],
      ),
    'getConsents' : IDL.Func([], [IDL.Vec(Consent)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getSBT' : IDL.Func([], [IDL.Opt(SoulboundToken)], ['query']),
    'getUserChatSessions' : IDL.Func([], [IDL.Vec(ChatSessionView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProfile' : IDL.Func([Profile], [], []),
    'updateSessionInference' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'verifySBT' : IDL.Func([IDL.Principal], [], []),
    'verifyUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };